[package]
name = "gosper"
version = "0.1.0"
authors = ["Guillaume Jacquenot <guillaume.jacquenot@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "^0.2.15"